version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: yuhenadit-tailadmin-laravel:beta
    ports:
      - "8090:8090"
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
