name: Laravel application (MySQL)
run-name: Build, Push and Deploy image tailadmin laravel
on:
  push:
    branches:
      - main
env:
  IMAGE_NAME: "yuhenadit/yuhenadit-tailadmin-laravel:beta"
jobs:
  run-mysql-in-docker:
    runs-on: self-hosted
    steps:
      - name: Delete container mysql if exist
        continue-on-error: true
        run: docker rm -f $(docker ps -a | grep 'mysql\|laravel' | awk '{print $1}')
      - name: Running mysql in container
        run: docker run -d --name mysql -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=tailadmin_laravel -p 3306:3306 mysql:5.7
      - name: List docker container
        run: docker ps -a

  build-push-image:
    needs: run-mysql-in-docker
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build and Push Docker image
        run: |
          docker buildx build --platform linux/amd64 -t $IMAGE_NAME --push .

  deploy-laravel:
    needs: build-push-image
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: Stop and remove existing container
        run: docker-compose down --rmi all
      - name: Start container
        run: docker-compose up -d
      - name: Setup environment
        run: ./setup_env.sh
